services:
  backend:
    build:
      context: ./backend
    container_name: wealthcalc-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - wealthcalc-net

  frontend:
    build:
      context: ./frontend
    container_name: wealthcalc-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - wealthcalc-net

networks:
  wealthcalc-net:
    driver: bridge